---
- name: Destruction des VMs
  hosts: localhost
  connection: local
  tasks:

    - name: Suppression des VMs
      community.general.lxd_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ groups['managers'] + groups['workers'] }}"

    - name: Suppression des bridges
      become: yes
      command: brctl delbr {{ item }}
      with_items:
        - br1
        - br2
...
