---
- name: Setup LXD Infrastructure
  hosts: local_host
  roles:
    - lxd_setup

- name: Common Configuration for all containers
  hosts: lxd_containers
  roles:
    - common

- name: Configure Redis
  hosts: redis_group
  roles:
    - redis

- name: Configure Web Nginx Servers
  hosts: web_nginx_group
  roles:
    - web_nginx

- name: Configure Web Apache Server
  hosts: web_apache_group
  roles:
    - web_apache

- name: Configure WAF Servers
  hosts: waf_group
  roles:
    - waf

- name: Configure HAProxy
  hosts: haproxy_group
  roles:
    - haproxy
