---
- name: Setup LXD Infrastructure
  hosts: local_host
  gather_facts: yes
  roles:
    - lxd_setup

- name: Configure Containers
  hosts: lxd_containers
  gather_facts: no
  pre_tasks:
    - name: Wait for python in container
      raw: test -e /usr/bin/python3
      register: python_check
      until: python_check.rc == 0
      retries: 30
      delay: 5
    - name: Gather facts manually
      setup:
  roles:
    - common

- name: Configure Redis
  hosts: redis_group
  roles:
    - redis

- name: Configure Web Nginx Servers
  hosts: web_nginx_group
  roles:
    - web_nginx

- name: Configure Web Apache Server
  hosts: web_apache_group
  roles:
    - web_apache

- name: Configure WAF Servers
  hosts: waf_group
  roles:
    - waf

- name: Configure HAProxy
  hosts: haproxy_group
  roles:
    - haproxy
